# Change these first
owner: Alvarohf # Your GitHub organization or username, where this repository lives
repo: sites-status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Planeta Fascinante
    url: https://planetafascinante.com
  - name: Help Metaverse
    url: https://helpmetaverse.com
  - name: Cañada el Espinar
    url: https://cañadaespinar.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
baseUrl: /sites-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sites status
  introTitle: "**My sites monitor** An uptime monitor to manage my sites."
  introMessage: This site has been done using upptime template that allows you to manage all your sites in an static page for free and with Github Actions.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
